language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - nose2 --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false